### ISSUE TITLE
How to call OtpGeneratingAuthenticationProvider in SpringSecurityConfiguration

### ISSUE THREAD

**Issue by venkataramu** [upcrob/spring-security-otp#3]
Hi @upcrob ,
I want to add 2fa filters in below spring security configuration call

**Comment by upcrob** [comment]
I believe you'll want to configure the `OtpValidationFilter` in that `configure()` method by adding it to your filter chain.  The `OtpGeneratingAuthenticationProvider` gets configured where you would normally setup implementations of `AuthenticationProvider`, but it's been long enough since I've worked with Spring where I can't tell you offhand (the Spring docs should be able to help you with this, though).  The top-level README should give you some idea of how the individual parts of the plugin fit together: https://github.com/upcrob/spring-security-otp/blob/master/README.md

If memory serves, the primary classes that interface with Spring are `OtpValidationFilter` and `OtpGeneratingAuthenticationProvider`, so you'll need to configure/inject them directly into the framework.  The other classes are specific to the OTP plugin.

I haven't tested the plugin on recent versions of Spring, however, so there may or may not be compatibility issues.
